{
  "Id": "402e8573-bd4d-4c15-aad6-59d49c437b3b",
  "Name": "New Document",
  "Nodes": [
    {
      "Top": 140,
      "Left": 96,
      "Node": {
        "Id": "e9fee91d-5781-4be0-b797-94a40a6661a9",
        "Name": "aaa"
      }
    },
    {
      "Top": 183,
      "Left": 336,
      "Node": {
        "Id": "b723b847-4e65-4610-8e94-f42a3f40aa9e",
        "Name": "bbb"
      }
    },
    {
      "Top": 400,
      "Left": 400,
      "Node": {
        "Id": "58b13d5c-07a7-41ae-a8e7-578f126fa658",
        "Name": "ccc"
      }
    },
    {
      "Top": 400,
      "Left": 600,
      "Node": {
        "Id": "6beac651-a263-4c18-a18e-321267c4d320",
        "Name": "ddd"
      }
    }
  ],
  "Links": [
    {
      "X1": 121,
      "Y1": 165,
      "X2": 361,
      "Y2": 208,
      "Link": {
        "Id": "c2b770a9-d4ba-45f7-81be-d74a6446bfd8",
        "Start": "e9fee91d-5781-4be0-b797-94a40a6661a9",
        "End": "b723b847-4e65-4610-8e94-f42a3f40aa9e",
        "Cost": 20
      }
    },
    {
      "X1": 361,
      "Y1": 208,
      "X2": 425,
      "Y2": 425,
      "Link": {
        "Id": "e2fe4bf3-265a-4484-933b-62f0904fbb5b",
        "Start": "b723b847-4e65-4610-8e94-f42a3f40aa9e",
        "End": "58b13d5c-07a7-41ae-a8e7-578f126fa658",
        "Cost": 10
      }
    }
  ],
  "Start": "e9fee91d-5781-4be0-b797-94a40a6661a9",
  "End": "b723b847-4e65-4610-8e94-f42a3f40aa9e"
}