{
  "Id": "ebeac3a2-2dab-4fa4-8179-64d9776fe9b1",
  "Name": "New Document",
  "Nodes": [
    {
      "Top": 139,
      "Left": 178,
      "Node": {
        "Id": "e9fee91d-5781-4be0-b797-94a40a6661a9",
        "Name": "aaa"
      }
    },
    {
      "Top": 133,
      "Left": 525,
      "Node": {
        "Id": "b723b847-4e65-4610-8e94-f42a3f40aa9e",
        "Name": "bbb"
      }
    },
    {
      "Top": 400,
      "Left": 400,
      "Node": {
        "Id": "58b13d5c-07a7-41ae-a8e7-578f126fa658",
        "Name": "ccc"
      }
    },
    {
      "Top": 400,
      "Left": 600,
      "Node": {
        "Id": "6beac651-a263-4c18-a18e-321267c4d320",
        "Name": "ddd"
      }
    },
    {
      "Top": 590,
      "Left": 558,
      "Node": {
        "Id": "10ca2291-ed4d-40b7-a05f-d383bb7f0ab7",
        "Name": "eee"
      }
    }
  ],
  "Links": [
    {
      "X1": 203,
      "Y1": 164,
      "X2": 550,
      "Y2": 158,
      "Link": {
        "Id": "c2b770a9-d4ba-45f7-81be-d74a6446bfd8",
        "Start": "e9fee91d-5781-4be0-b797-94a40a6661a9",
        "End": "b723b847-4e65-4610-8e94-f42a3f40aa9e",
        "Cost": 20
      }
    },
    {
      "X1": 550,
      "Y1": 158,
      "X2": 425,
      "Y2": 425,
      "Link": {
        "Id": "e2fe4bf3-265a-4484-933b-62f0904fbb5b",
        "Start": "b723b847-4e65-4610-8e94-f42a3f40aa9e",
        "End": "58b13d5c-07a7-41ae-a8e7-578f126fa658",
        "Cost": 10
      }
    },
    {
      "X1": 625,
      "Y1": 425,
      "X2": 550,
      "Y2": 158,
      "Link": {
        "Id": "2fe97bfe-15f5-454f-b44b-bbc2fe3eb69b",
        "Start": "6beac651-a263-4c18-a18e-321267c4d320",
        "End": "b723b847-4e65-4610-8e94-f42a3f40aa9e",
        "Cost": 10
      }
    },
    {
      "X1": 625,
      "Y1": 425,
      "X2": 425,
      "Y2": 425,
      "Link": {
        "Id": "239ea865-471d-4be8-91af-7bcbf3e0ce00",
        "Start": "6beac651-a263-4c18-a18e-321267c4d320",
        "End": "58b13d5c-07a7-41ae-a8e7-578f126fa658",
        "Cost": 10
      }
    },
    {
      "X1": 583,
      "Y1": 615,
      "X2": 425,
      "Y2": 425,
      "Link": {
        "Id": "e319bcda-6d1f-4b51-a8fa-b7ad876bb940",
        "Start": "10ca2291-ed4d-40b7-a05f-d383bb7f0ab7",
        "End": "58b13d5c-07a7-41ae-a8e7-578f126fa658",
        "Cost": 10
      }
    },
    {
      "X1": 583,
      "Y1": 615,
      "X2": 625,
      "Y2": 425,
      "Link": {
        "Id": "a4e48bb9-45f0-4c45-9fbd-7cfa1381a067",
        "Start": "10ca2291-ed4d-40b7-a05f-d383bb7f0ab7",
        "End": "6beac651-a263-4c18-a18e-321267c4d320",
        "Cost": 10
      }
    }
  ],
  "Start": "e9fee91d-5781-4be0-b797-94a40a6661a9",
  "End": "b723b847-4e65-4610-8e94-f42a3f40aa9e"
}